//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExifReader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExifReader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0x0000,PropertyTagGpsVer
        ///0x0001,PropertyTagGpsLatitudeRef
        ///0x0002,PropertyTagGpsLatitude
        ///0x0003,PropertyTagGpsLongitudeRef
        ///0x0004,PropertyTagGpsLongitude
        ///0x0005,PropertyTagGpsAltitudeRef
        ///0x0006,PropertyTagGpsAltitude
        ///0x0007,PropertyTagGpsGpsTime
        ///0x0008,PropertyTagGpsGpsSatellites
        ///0x0009,PropertyTagGpsGpsStatus
        ///0x000A,PropertyTagGpsGpsMeasureMode
        ///0x000B,PropertyTagGpsGpsDop
        ///0x000C,PropertyTagGpsSpeedRef
        ///0x000D,PropertyTagGpsSpeed
        ///0x000E,PropertyTagGpsTrackRef
        ///0x000F,PropertyTagGpsTrack
        ///0x0010, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string types {
            get {
                return ResourceManager.GetString("types", resourceCulture);
            }
        }
    }
}
